version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - printf "y" | apt-get install python-dev python3-dev
      - printf "y" | apt-get install libmysqlclient-dev
      # - aws cloudformation package --template-file serverless.template --s3-bucket 1221-cf-bucket --output-template-file transformed-template.json
      # - aws cloudformation deploy --template-file transformed-template.json --stack-name devesh-zappa-final --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset
      - python -m venv venvzappa
      - . venvzappa/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pymysql
      - pip3 install mysqlclient
      - zappa update dev
      # - printf "y" | zappa undeploy
      # - zappa deploy dev
      # - printf "\n\n\n\n\n" | zappa init
      # - ls -lrt
      # - zappa package dev -o pim_web.zip
      # - apt-get install unzip
      # - mv pim_web.zip ../
      # - cd ../
      # - rm -rf pim_app
      # - unzip -o pim_web.zip
      # - rm -rf pim_web.zip
      # - ls -lrt
      - zappa manage dev migrate
      - zappa invoke --raw dev "from django.contrib.auth.models import User; User.objects.create_superuser('admin', 'admin@mathem.se', 'admin')"
    finally:
      - zappa tail dev --since 1h

      