version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - python -m venv venvzappa
      - . venvzappa/bin/activate
      - pip install -r requirements.txt
      - printf "\n" | zappa undeploy
      - zappa deploy dev
      # - printf "\n\n\n\n\n" | zappa init
      # - ls -lrt
      # - zappa package dev -o pim_web.zip
      # - apt-get install unzip
      # - mv pim_web.zip ../
      # - cd ../
      # - rm -rf pim_app
      # - unzip -o pim_web.zip
      # - rm -rf pim_web.zip
      # - ls -lrt
      # - aws cloudformation package --template-file serverless.template --s3-bucket 1221-cf-bucket --output-template-file transformed-template.json
      # - aws cloudformation deploy --template-file transformed-template.json --stack-name pim-web-no-zappa --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset